### ISSUE TITLE
0.2.1.1 버전에서 404 버그가 수정되지 않음

### ISSUE THREAD

**Issue by myoun** [junah201/velog-helper#18]
0.2.1.1에서 #16 이 고쳐지지 않았습니다.
![image](https://user-images.githubusercontent.com/76814120/193072879-9b0740af-3391-4378-8cdf-c87579d79b01.png)
![image](https://user-images.githubusercontent.com/76814120/193072945-6d9fc3b6-22eb-419e-b219-9b37092f8b5c.png)

**Comment by junah201** [comment]
@myoun 배포 버전에 패치가 적용이 안되어 있었네요.
적용해서 배포 완료하였습니다. 크롬 확장프로그램 목록에서 삭제 후 재설치하시면 버그 수정되어 있습니다.
이슈 감사합니다 👍👍👍

**Comment by myoun** [comment]
![image](https://user-images.githubusercontent.com/76814120/194705337-39e5c8e2-8868-4297-8227-df92225655f6.png)
정상적으로 해결된 것 같지 않습니다.
![image](https://user-images.githubusercontent.com/76814120/194705360-17f6fa9f-41a6-48f8-b16b-1b146adee68e.png)
알림 목록에서 글을 클릭하면, 파일에 액세스 할 수 없다고 뜨는데, 그 링크를 새 탭에서 열어보면, 사진 1과 같은 url로 연결이 됩니다.

**Comment by junah201** [comment]
기존 수정사항에서는 팝업창에서 새 글 알림 링크가 정상적으로 이동하지 못하는 버그를 수정하였습니다.
크롬 확장프로그램 배포는 신청해두었으나 아직 승인 받기까지 시간이 걸릴 것으로 보입니다.

**Comment by junah201** [comment]
@myoun 배포 완료하였습니다. 크롬 확장프로그램 목록에서 삭제 후 재설치하시면 수정되어있습니다.
