### ISSUE TITLE
최초 연동 시 과거 글들이 새 글인것처럼 메일로 쏟아짐

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#25]
![CleanShot 2022-11-21 at 11 58 43@2x](https://user-images.githubusercontent.com/26613280/202953968-b432ab38-5dd8-4758-9ca3-845b36f266a2.png)

"이제부터 올라올 글"이 메일로 날라오길 기대했는데, 기존의 게시물들을 긁어옴. 어떤 식으로든 구독 시작 날짜를 기록해야 할 것 같음

**Comment by junah201** [comment]
@roeniss 
엇, 기존 이메일 기능을 개발하기 전에 이미 저는 왼만한 블로그를 대부분 북마크 해놓았었어서 이런 문제가 있는줄 몰랐네요 ㅠㅠ
아무도 북마크 안했을만한 벨로그를 북마크 하니 바로 재현 가능하네요.
빠르게 수정하도록 하겠습니다
이슈 감사합니다 !!

**Comment by junah201** [comment]
블로그 등록 시 포스트를 가져오는 로직과, 꾸준히 새로운 글이 있는지 확인하는 로직이 분리가 안되서 생기는 버그로 확인했으며, 시험 끝나고 빠르게 처리할겠습니다.. (12월 14일 이전에)

간단하게 해당 블로그가 처음 등록된 블로그인지 확인하는 칼럼을 블로그 데이터베이스에 추가하고, 새로 블로그가 등록되었을 때 바로 모든 글을 가져오며, 처음 등록된 블로그가 아니라고 체크하면 될 것 같습니다.

**Comment by roeniss** [comment]
감사합니다 ㅎㅎㅎ
