### ISSUE TITLE
수신 거부 해제

### ISSUE THREAD

**Issue by myoun** [junah201/velog-helper#28]
메일로 수신거부를 눌렀을때, 이를 어떻게 해제하나요?

**Comment by junah201** [comment]
@myoun 
수신 거부를 눌렀을 때 연결되는 페이지의 링크는
`https://velog-helper.herokuapp.com/subscription/{유저id}?is_subscribe=false` 로 나오는데
아래 링크와 같이 맨 뒤 부분을 true로 바꿔서 접속하시면 수신처리됩니다.
`https://velog-helper.herokuapp.com/subscription/{유저id}?is_subscribe=true` 

이 부분은 생각 못했던 부분이네요. 수신 처리할 수 있는 부분을 팝업-설정에 추가하도록 할께요.

**Comment by myoun** [comment]
답변 감사합니다.

**Comment by myoun** [comment]
> @myoun 
> 수신 거부를 눌렀을 때 연결되는 페이지의 링크는
> `https://velog-helper.herokuapp.com/subscription/{유저id}?is_subscribe=false` 로 나오는데
> 아래 링크와 같이 맨 뒤 부분을 true로 바꿔서 접속하시면 수신처리됩니다.
> `https://velog-helper.herokuapp.com/subscription/{유저id}?is_subscribe=true` 
> 
> 이 부분은 생각 못했던 부분이네요. 수신 처리할 수 있는 부분을 팝업-설정에 추가하도록 할께요.

혹시 유저id를 쉽게 확인하는 방법이 있을까요?

**Comment by junah201** [comment]
@myoun 
사실 크롬 개발자도구 Storage에서 잘 찾으면 찾을 수 있겠지만

크롬에서 로그인이 되어있다면, 크롬유저id를 그대로 사용하지만
타브라우저나 로그인이 안되어있다면, 설치 당시 시간과 ip등을 조합해서 만들기 때문에

수신 거부를 다시 눌러서 확인하는게 가장 빠른 방법인 것 같습니다.

**Comment by junah201** [comment]
더 이상 수신 거부를 눌렀을 때 단순히 text 응답이 아닌 html 응답으로 사용자 경험을 개선하였습니다.

![image](https://user-images.githubusercontent.com/75025529/208304792-266689e9-2516-4301-bbfc-efac81b6821c.png)

![image](https://user-images.githubusercontent.com/75025529/208304774-31d76168-ef11-4778-b2ba-0b98b144fd51.png)
