### ISSUE TITLE
[feature proposal] 글이 수정된 경우에도 노티를 받고 싶습니다.

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#29]
![CleanShot 2022-12-07 at 17 24 07@2x](https://user-images.githubusercontent.com/26613280/206126560-5b7cb0c6-9f59-40d3-83d8-f89c2328abd1.png)

이거 때문입니다.

[link](https://velog.io/@mowinckel/Dick-Side-of-the-Dev)

**Comment by roeniss** [comment]
정확하게 어떤 부분이 달라졌는지, 를 메일에 담으려면 조금 복잡하겠으나, 

단순히 내용이 바뀌었다 정도만 얘기하고 싶다면 글마다 hashcode 를 따는 방법이 좋을 것 같습니다.

```python
# pseudo code
   body = get_content_body(content_id)
   hash = make_hash_code(body)
   stored_hash = find_stored_hash_from_db(content_id)
   if stored_hash is None: 
      # new post
   else: 
      if stored_hash == hash:
         pass # nothing new
      else: 
         save_new_hash_to_db(content_id, hash)
         send_mail_for_content_update(users, content_id)
```

**Comment by junah201** [comment]
@roeniss 
Velog API에서 각 포스트마다 `released_at` 과 `updated_at`을 제공해주고 있어서 해당 값을 기준으로 해당 글이 업데이트되었다는 것은 확인 할 수 있습니다.

또한 글이 수정되었을 때 Velog API에서 알림을 주는게 아니기 때문에 직접 api에 요청을 보내면서 해당 글이 업데이트되었는지 확인해야하기 때문에 모든 글을 자주 확인하는 것은 불가능하고
`한번 수정된 글은 계속해서 수정될 확률이 높다` 라는 생각하에 한번이라도 수정된 글은 더욱 한번도 수정안된 글 보다 자주 확인하고, 시간이 지나면 확인해야하는 글이 너무 많아지기 때문에 최근 몇개월 이내의 글만 확인하는 식으로 처리해야할 것 같습니다. 

12월 13일에 시험이 끝나면 서버 이전하면서 간단하게 개발해볼께요 !

**Comment by roeniss** [comment]
아 그런 필드가 제공되고 있군요! 좋네요. @junah201 

>  한번이라도 수정된 글은 더욱 한번도 수정안된 글 보다 자주 확인하고

이것도 (현시점에서) 오버엔지니어링 같아서, 최근 몇개월~ 부분만 우선적으로 구현해도 좋을것 같습니다. 감사합니다 :bow:

**Comment by roeniss** [comment]
> 12월 13일에 시험이 끝나면 서버 이전하면서 간단하게 개발해볼께요 !

맨 위에 제공한 포스팅이 업데이트 되었습니다. 개발하실 때 레퍼런스로 쓰시면 될 것 같아요.

**Comment by junah201** [comment]
@roeniss
처음 제안해주신 대로 hashcode 이용해서 제작하였으며
서버 배포 시간으로부터 12시간마다 새로운 글이 있는지 확인하여 수정 알림 메일을 보내줍니다.

또한 맨 처음에는 전체 기능으로 열어둘 생각이었으나 별 내용 없는 수정 메일이 너무 많이 갈 것 같아서
일단은 저랑 @roeniss 에게만 수정 알림 메일을 보내며
모빈켈, 테스트용 블로그 두 개만 확인하도록 개발하였습니다.

이슈는 며칠 사용해보고 문제없으면 그때 닫을게요.

**Comment by roeniss** [comment]
@junah201 감사합니다! 수고하셨어요~ 시험은 잘 보셨나요? :D

그런데 테스트가 필요하다면 junah201 님 블로그에 테스트용 글을 만들어서 해봐도 좋을 것 같네요 (그런 식으로 일종의 테스트 환경을 구축해 두는 것도 좋을 것 같아요. velog dev server 를 기대하기는 힘드니까)

그리고 왜 각 포스트의 updated_at 를 사용하지 않기도 결정하셨는지 궁금합니다.

**Comment by junah201** [comment]
@roeniss 
오해의 소지가 있었네요 [테스트용 블로그](https://velog.io/@fdsfdafdsf)를 하나 파서 글을 올리면서 사용하고 있어요.

그리고 `updated_at`를 저는 글이 수정되었을 때 바뀌고, 댓글을 달았을 때는 안 바뀌길래 글이 수정되었을 때만 바뀌는 필드인 줄 알았는데, 말 그대로 DB에 저장할 때 일반적으로 쓰는 `updated_at`이어서 좋아요 등 여러 가지에도 바뀌길래 어쩔 수 없이 `hashcode`를 따서 작업하게 되었어요.

**Comment by roeniss** [comment]
![CleanShot 2022-12-18 at 00 05 16@2x](https://user-images.githubusercontent.com/26613280/208248362-4d018783-4042-431d-b1b8-a638a815237b.png)

@junah201 ㅋㅋㅋㅋㅋㅋ 놀랍게도 글이 이렇게 읽혔습니다 죄송해욬ㅋㅋㅋㅋㅋㅋㅋ

아~ DB 저장의 필드군요. 리버스 엔지니어링까지 하셨네요 ㅋㅋ

**Comment by junah201** [comment]
![image](https://user-images.githubusercontent.com/75025529/209467450-5187e6b4-e530-4570-b962-2c791f878397.png)
수정 알림도 정상적으로 오네요

**Comment by roeniss** [comment]
@junah201  네 저도 확인했습니다. GA (general available) 가능한가요?

**Comment by junah201** [comment]
@roeniss #37 을 먼저 작업 중이고,
즐겨찾기한 모든 블로그가 아니라, 즐겨찾기를 한 후에도 따로 설정을 해야지 수정 알림을 받을 수 있도록 하려고 합니다.
곧 버전을 제대로 올리면서 한번에 패치하도록 할께요.

아 그리고 상관 없는 내용이긴한데, 위에 올려주신 사진처럼 강조 표시는 어떤 프로그램 사용하시나요?

**Comment by roeniss** [comment]
@junah201 cleenshotX 씁니다

**Comment by junah201** [comment]
감사합니다. 한번 써볼께요 !!

**Comment by roeniss** [comment]
@junah201 코드에 아직 `target_user` 가 [존재하는 것 같은데](https://github.com/junah201/velog-helper/blob/main/backend/app/tasks/edited_post.py#L13), 해당 코드는 무관하고 실제로는 모든 유저한테 발송되는 건가요?

**Comment by junah201** [comment]
@roeniss
다른 프로젝트에 집중하느라 신경을 못쓰고 있었네요.
이번 프로젝트가 2 3일이면 끝날 것 같아서 검색 기능 제작하면서 같이 수정해볼께요
