### ISSUE TITLE
Velog Helper 확장의 업데이트가 필요할 때 유저에게 알리는 기능이 필요합니다.

### ISSUE THREAD

**Issue by junah201** [junah201/velog-helper#31]
심각한 버그 등이 Velog Helper의 업데이트로 인해서 수정되었을 때 빠른 업데이트가 필요한데 이때 유저에게 알릴 수 있는 기능이 필요합니다.

**생각하고 있는 방안**
- 전체 유저에게 이메일로 통보하기 (이메일이 없거나, 구독 해지 중인 고객에게는 알림 전송 불가)
- #15 와 같은 방식으로 Velog 사이트 내부에 표시되는 알림 상단에 새로운 버전이 있다고 알리기

**Comment by myoun** [comment]
https://developer.chrome.com/docs/apps/autoupdate/
참고해보시는것도 좋을 것 같네요

**Comment by junah201** [comment]
이런 기능이 있는지 처음 알았네요. 한번 확인해볼께요! 감사합니다 (꾸벅)

**Comment by roeniss** [comment]
[네이버 영어사전 익스텐션](https://chrome.google.com/webstore/detail/%EB%84%A4%EC%9D%B4%EB%B2%84-%EC%98%81%EC%96%B4%EC%82%AC%EC%A0%84-naver-english-di/jfibpeiddefellcfgnijpcpddoimbdij)은 자동 업데이트 후 배너까지 띄워주더군요. ("4.3 업데이트 안내" 식으로... 누르면 작은 창이 나오거나 별도 사이트로 redirect 되었던 것 같습니다.) @junah201
