### ISSUE TITLE
백엔드 개발환경 세팅

### ISSUE THREAD

**Issue by myoun** [junah201/velog-helper#32]
현재 백엔드 개발환경을 세팅하고 있습니다.

```py
SQLALCHEMY_DATABASE_URL = os.environ.get("CLEARDB_DATABASE_URL")
MAIL_SENDER = os.environ.get("MAIL_SENDER")
MAIL_PASSWARD = os.environ.get("MAIL_PASSWARD")
BACKEND_SERVER_URL = os.environ.get("BACKEND_SERVER_URL")
```
https://github.com/junah201/velog-helper/blob/main/backend/app/common/config.py

환경변수 세팅을 어떻게 해야할지 감이 안잡혀서 이슈 남겨봅니다.

데이터베이스 URL부분은 알겠는데 나머지 부분이 헷갈리네요.
그리고 데이터베이스 PW는 필요가 없는건가요?

**Comment by junah201** [comment]
@myoun 
먼저 **SQLALCHEMY_DATABASE_URL** 은 `mysql://username:password@host정보/데이터베이스이름` 이런식으로 적어주시면 되고
**MAIL_SENDER**는 알림 메일을 보낼 메일 주소를 적어주시고
**MAIL_PASSWARD**에는 구글계정 - 보안 - Google에 로그인 - 2단계 인증 부분에서 key를 받아서 공백 없이 적어주시면 됩니다. (아래 사진 참고)
**BACKEND_SERVER_URL**은 실제 호스팅되는 서버의 주소를 적어주시면 되는데, 이 부분은 알림 메일에서 수신거부를 할 때 서버에 요청을 보내기 위해서 사용되니 단순 테스트를 위해서는 다른 값을 적어주셔도 됩니다.

![image](https://user-images.githubusercontent.com/75025529/208412490-274f4824-12ce-4c1e-8b91-06ed2ce82ef2.png)

**Comment by myoun** [comment]
@junah201 
https://github.com/junah201/velog-helper/blob/main/backend/app/main.py#L19
에서 VELOG_HELPER_VERSION을 import하지만
https://github.com/junah201/velog-helper/blob/main/backend/app/common/consts.py
에는 VELOG_HELPER_VERSION이 없습니다.
사용하지 않는 변수인것 같긴 한데 이것 때문에 오류가 나서 문의 드립니다.

**Comment by myoun** [comment]
아 그리고 메일도 한번 확인해주시면 감사하겠습니다 :)

**Comment by junah201** [comment]
@myoun 
#31 관련하여 기능 개발을 간단하게 하다가 실수로 커밋한 것 같네요. cosnt 파일에 추가했습니다.

**Comment by myoun** [comment]
@junah201 
```yml
DISCORD_WEBHOOKS_NEW_POST_UPLOAD_LOG = os.environ.get("DISCORD_WEBHOOKS_NEW_POST_UPLOAD_LOG")
DISCORD_WEBHOOKS_POST_UPDATE_LOG = os.environ.get("DISCORD_WEBHOOKS_POST_UPDATE_LOG")
```
최근에 추가된 요기에는 무엇을 넣어야되나요?

**Comment by junah201** [comment]
@myoun 
디스코드 채널의 웹 훅을 넣어주시면 되는데, 디스코드 채널에서 `우클릭` - `채널 편집` - `연동` - `웹후크` - `새 웹후크` - `링크 복사`로 복사해서 넣어주시면 됩니다.

새 글이 업로드되거나, 수정되었을 때 채널에 로그를 남기는 기능이에요.

근데 이번에 1.0.0 패치되면서 서버를 AWS lambda로 이전하면서 기존 코드가 그대로 로컬에서도 작동할지는 모르겠네요 ㅠ

**Comment by myoun** [comment]
@junah201 
AWS lambda로 이전하면서 신규 포스트 받아오는거랑 수정된 포스트 받아오는 기능이 분리되어서 작동을 제대로 안하네요.
