### ISSUE TITLE
[question] 버저닝 체계가 궁금합니다

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#35]
네자릿수 버전 표기는 처음 보는 것 같아서, 따로 기준이나 레퍼런스가 있으신지 궁금합니다 @junah201

**Comment by junah201** [comment]
결론만 먼저 말하자면 특별한 이유는 없었지만 어쩌다보니...이고

처음에는 0.1.0으로 시작해서 기능이 완성되면 1.0.0으로 올릴 생각을 하고 있었지만
중간에 버전업을 하기에는 너무 사소한 버그여서 `0.2.1`에서 `0.2.1.1`으로 올리게 되었고
이후 시험기간 등 오랜 시간동안 큰 관리가 없었다보니 `0.2.1.1`에서 `0.2.1.2` ... `0.2.1.8` 으로 쭉 올리게 되었어요.

다시 생각해보니 버전이 조금 이상하긴 하네요.
아래와 같이 지금 생각하고 있는 업데이트를 전부 한 후에 1.0.0으로 올려보도록 할께요.

---

**지금 생각하고 있는 업데이트**
- Popup 디자인 개선
- 프로그램 설치 시 새 탭을 자동으로 띄우고, 해당 탭에서 사용법 설명 및 이메일 주소 입력
- 오래된 데이터 자동 삭제 및 DB 최적화
- 12.31까지 AWS Lambda로 서버 이전

**Comment by roeniss** [comment]
호기심 풀어주셔서 감사합니다
