### ISSUE TITLE
블로그 게시물 내에서 북마크 등록

### ISSUE THREAD

**Issue by myoun** [junah201/velog-helper#36]
![image](https://user-images.githubusercontent.com/76814120/208928523-39ca7d15-1550-486e-a72f-2bb3fca43faa.png)
위 이미지 같은 느낌으로 블로그 내에서 북마크 등록을 하는건 어떤가요?
일일이 사용자 페이지로 들어가야되는 번거로움이 있어서 저기서 등록을 하는것도 나쁘지 않다고 생각합니다.

**Comment by junah201** [comment]
@myoun 
글 맨 하단에 북마크 버튼이 생기긴하지만
![image](https://user-images.githubusercontent.com/75025529/208941661-5ea9fd56-95b4-41c6-a4c4-b23d4f2ceafb.png)

상단에 생기는 것도 좋은 것 같아요 !!

**Comment by junah201** [comment]
몇가지 업데이트를 더 포함해서 크롬 웹스토어에 배포하겠습니다.

**Comment by junah201** [comment]
크롬 웹스토어에 업로드하였고, 몇일 내로 승인되어 배포될 예정입니다.
