### ISSUE TITLE
최초 설치 시 사용법을 알려주는 팝업창이 필요합니다.

### ISSUE THREAD

**Issue by junah201** [junah201/velog-helper#37]
`browser.runtime.onInstalled.addListener(() => {})`을 이용하여 팝업창을 띄우는 생각을 가지고 있고
팝업창에는 아래 내용이 포함될 예정입니다.'

- 북마크 추가 방법
- 알림 확인 방법
- 팝업창 확인 방법
- 이메일 설정 방법

Github Projects 대신에 이슈를 쓰는 느낌이 있긴하지만 일단 기능 추가에는 이슈를 남기고 개발을 진행하려고 합니다.

**Comment by myoun** [comment]
팝업창 대신 새 탭을 띄우는 방식은 어떤가요?

**Comment by junah201** [comment]
네네, FastAPI 백엔드 서버에 정적 html 파일을 올려놓아서 해당 링크로 새 탭을 열려고 생각하고 있어요
근데 새 탭에 들어갈 html 코드를 아직 제작하지 않아서 늦어지고 있어요.

```js
// 사용 설명서 페이지를 새 탭으로 열기
browser.tabs.create({
	url: `${Constants.BACKEND_URL}/guide`,
});
```

**Comment by junah201** [comment]
https://velog-helper.herokuapp.com/guide

**Comment by junah201** [comment]
크롬 웹스토어에 업로드하였고, 몇일 내로 승인되어 배포될 예정입니다.
