### ISSUE TITLE
게시물 북마크 기능

### ISSUE THREAD

**Issue by myoun** [junah201/velog-helper#39]
유저가 아닌 특정 게시글을 북마크하는 기능을 제안합니다.
알림을 받기 위한 용도가 아닌, 특정 게시글을 나중에도 다시 방문하고 싶은 경우에 쓰일 수 있는 기능이 필요합니다.
`즐겨찾기`라고 생각할수도 있겠네요.

**Comment by junah201** [comment]
`벨로그 프로필` 클릭 - `읽기 목록` 에서 좋아요한 게시물의 목록을 볼 수 있기 때문에 이미 Velog 내부에 비슷하게 구현되어 있기 때문에 불필요한 기능이라고 생각됩니다.

**Comment by myoun** [comment]
오 그렇군요
이슈 닫겠습니다.
