### ISSUE TITLE
[건의] 홍보가 더 잘 되었으면 좋겠습니다

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#42]
https://news.hada.io/show

https://disquiet.io/

https://www.facebook.com/groups/codingeverybody

제가 아는 건 이정도인데, 이를 포함한 여러 사이트들에 홍보글을 올려보면 어떨까요. 

유저가 늘어나면 기능 발전에도 도움이 되고, 여러 이슈가 생겨서 성장에도 도움이 되지 않을까 싶습니다. @junah201

**Comment by junah201** [comment]
다른 프로젝트에 집중하느라 신경을 많이 못쓰고 있었네요 ㅠㅠ

위 사이트들 포함해서 여러군데 홍보글 남겨볼께요 !!

**Comment by junah201** [comment]
https://disquiet.io/product/velog-helper

디스콰이엇에 올렸던 홍보글이 업로드되었습니다.

GeekNews는 가입 후 1주일이 지나야 홍보가 가능해서 기다리고 있어요.

**Comment by roeniss** [comment]
@junah201 너무 멋있습니다. 항상 뒤에서 꿍시렁대는 역할만 하는 것 같아 좀 죄송스럽군요. 제가 도울만한 일이 있을까요?
