### ISSUE TITLE
google 검색을 이용한 velog 내부 검색 기능 강화

### ISSUE THREAD

**Issue by junah201** [junah201/velog-helper#43]
velog 사이트 내부에서 검색을 하다 보면 검색이 내가 원하던 결과가 잘 안나오는 문제가 있습니다.
따라서 저는 velog 사이트 내부 검색보다 `site:` 옵션을 이용해서 google 검색을 이용하는 편인데 
> ex, `리엑트 useState site:velog.io`  `mysql charset site:velog.io`

확장프로그램과 구글 서치 api를 이용해서 velog 내부 검색 결과를 구글 검색 결과로 바꿔주는 것에 대해서 어떻게 생각하는지 궁금합니다.

**Comment by myoun** [comment]
velog 내부 검색은... 끔찍합니다...

전 찬성합니다.

**Comment by myoun** [comment]
하지만, 기존 검색을 버리는 방안은 좋지 않아 보이네요

**Comment by junah201** [comment]
@myoun 
기존 검색은 유지하되 추가로 velog 내부에서 검색할 때 구글 검색 옵션을 제공하고 한번 구글 검색 옵션이 설정되어 있으면 새로고침해도 유지되도록 개발해볼께요 !

**Comment by roeniss** [comment]
@myoun @junah201 벨로그에 준비되어있는 검색 기능을 많이 안써봐서 질문드립니다. 내부 검색이 어떤 식으로 안좋나요? 체감해볼만한 예시 검색어가 있을까요?

**Comment by junah201** [comment]
@roeniss 
첫번째로는 일반적으로 검색을 할때 띄어쓰기 단위로 키워드를 분리해서 검색하는데
검색을 `A키워드 B키워드 C키워드` 로 하게 되면 A키워드가 들어간 글이 없더라도 B C 키워드를 기준으로 찾아서 결과를 보여주지만
velog에서는 전체 검색어를 하나의 string으로 묶어서 처리합니다. (코드 전체를 본것은 아니라서 정확하지 않을 수 있음)
(참고 [client search page](https://github.com/velopert/velog-client/blob/master/src/pages/SearchPage.tsx), [client search container](https://github.com/velopert/velog-client/blob/master/src/containers/search/SearchResult.tsx), [server search function](https://github.com/velopert/velog-server/blob/48c3a0e820e31ea1dfbc3f4a37be66e9dd0f0dd0/src/search/keywordSearch.ts))

따라서 예를 들어 velog helper로 검색하면 게시물이 나오지만
helper velog로 검색하면 게시물이 나오지 않습니다.

두번째로는 검색을 했을때 좋아요, 조회수 등의 기준이 적용되지 않습니다. 구글 검색에 velog helper를 검색하면 제가 쓴 홍보 게시글이 테스트용 게시글보다 먼저 뜨지만, velog 검색에서는 테스트용 게시글이 더 앞에 뜨는 문제가 있습니다.

**Comment by myoun** [comment]
> @myoun @junah201 벨로그에 준비되어있는 검색 기능을 많이 안써봐서 질문드립니다. 내부 검색이 어떤 식으로 안좋나요? 체감해볼만한 예시 검색어가 있을까요?

간단히 `kotlin`이라는 키워드로 검색해보셔도 아실 수 있습니다.
https://velog.io/search?q=kotlin

`kotlin`을 검색했는데 나오는 게시물은 이와 전혀 상관 없이 `kotlin`이라는 키워드가 본문에서 한번만 포함된 게시글이 검색 결과로 나오게 됩니다.

**Comment by myoun** [comment]
물론 아래로 좀 많이 내리면 관련 게시글이 나오긴 합니다만...

**Comment by junah201** [comment]
직접 Velog 처럼 각 입력값이 변할 때마다 요청을 보내서 검색 결과를 가져오고 싶었지만
구글 Search API의 하루 제한이 10000건인데 제한을 너무 쉽게 넘겨버려서 이 방법은 캐싱을 하거나, 아예 직접 검색 결과를 크롤링 하는 방식이 아니면 불가능했습니다.

따라서 버튼을 누르는 등의 방식으로 요청 수를 줄이자는 생각을 했고
![image](https://user-images.githubusercontent.com/75025529/214365765-ec32b738-0e38-4980-8b4a-4b04064f6857.png)

위 이미지와 같이 정상적으로 변경되지만 이렇게 검색 결과를 바꾼 상태로 입력값을 바꾸면 아래 이미지와 같이 바로 에러가 떠버려서
![image](https://user-images.githubusercontent.com/75025529/214365843-cc17f955-73d7-494a-a31d-ff73b8185910.png)

버튼을 누르면 google 검색에 `입력값 site:velog.io` 를 입력한 링크로 바로 이동시키는 것이 최선으로 보이는데 어떻게 생각하시나요?

**Comment by roeniss** [comment]
@junah201 상황을 잘 이해하지 못했습니다. 크롬 익스텐션으로 DOM 에 검색결과 엘리먼트를 붙인 뒤에 → 다른 검색어를 입력하니까 → 벨로그코드베이스에서 이 부분을 제대로 처리하지 못해서 에러가 발생했다는 것인가요?

**Comment by myoun** [comment]
그렇다면 현재 가이드 페이지처럼 따로 페이지를 만들어서 처리하는건 어떤가요?

**Comment by junah201** [comment]
@roeniss 

크롬 익스텐션을 통해서 기존 검색 결과가 표시되는 DOM에 표시되는 값을 바꾼 후에, 다시 검색어를 변경할 경우 벨로그코드베이스에서 에러가 발생해서 바로 페이지가 에러페이지로 넘어가더라고요. 리엑트 딴에서 나오는 문제 같은데

그래서 제가 생각하고 있는 방안은

1. 기존 검색 결과를 수정하는 것이 아닌 기존 검색 결과 위 쪽에 div 박스를 하나 더 만들어서 추가한다.
2. 버튼을 누르면 구글 검색 페이지로 입력된검색어를 검색한 상태로 이동시킨다.

정도인데...

2번이 구글 API 레이트리밋 같은 것도 고려할 필요도 없고 해서 편하긴한데
사용자 입장에서는 1번이 더 편해보여서 고민중이에요.

**Comment by roeniss** [comment]
@junah201  cc. @myoun 
> 2. 버튼을 누르면 구글 검색 페이지로 입력된검색어를 검색한 상태로 이동시킨다.

Q1. 위 말씀이 https://www.google.com/search?q=velog-helper+site%3Avelog.io 를 보여주겠다는 의미시죠? UX 너무 안좋은 것 같습니다.

> 1. 기존 검색 결과를 수정하는 것이 아닌 기존 검색 결과 위 쪽에 div 박스를 하나 더 만들어서 추가한다.

Q2. 위 말씀이 "DOM 을 조금 다른 방식으로 수정하면 벨로그 쪽 소스에 영향을 안미칠 것 같다"는 말씀이시죠? 이게 차라리 낫다고 생각합니다. 단순한 '게시글 목록' 형태의 UI 로도 충분히 좋은 정보를 제공할 것 같아요. 욕심을 좀 더 내보자면, 싫어하는 분도 있을 수 있으니까.. 이 기능을 on/off 할 수 있어야 할 것 같습니다 (검색창 근처에).

**Comment by junah201** [comment]
Q1. 네네, `검색쿼리 site:velog.io`로 검색된 구글 링크를 열어주는 방식도 생각 중이고, 저도 이 부분은 UX가 너무 안좋다고 생각해서 최후의 수단으로 남겨두려고요.

Q2. 구글 search API 제한도 있고 해서, 기존 검색 결과를 아예 대체하는 것보다 추가 검색 버튼을 만들어서 해당 버튼을 눌러야지 구글 검색으로 대체해서 보여주는 것으로 생각하고 있어요.

**Comment by junah201** [comment]
#51
