### ISSUE TITLE
[건의] 게시물 스크랩 기능이 추가되었으면 좋겠어요

### ISSUE THREAD

**Issue by kdomo** [junah201/velog-helper#44]
안녕하세요 준아님🙇🏻

velog에서 여러 게시물들을 돌다가 저장해놓고 보고 싶은 글이 생겼을 때,
전 보통 해당 링크를 따로 복사하여 따로 저장해놓곤 합니다.

velogHelper에 다른 사용자의 게시물을 스크랩 할 수 있는 기능이 있으면 좋을 것 같아서 이슈 남겨봅니다.

**Comment by junah201** [comment]
@kdomo 
#39 와 동일한 이슈인 것 같은데
유저 별로 북마크 폴더를 생성해서 폴더별로 분리해서 저장할 수 있도록 구성해볼께요 !

**Comment by roeniss** [comment]
이미 그러한 기능이 벨로그에 있는 줄 알았는데, 자세히 보니 '좋아요'와 '최근 본 글'은 있지만 '보관함'은 없네요!

**Comment by roeniss** [comment]
![CleanShot 2023-01-22 at 03 19 20@2x](https://user-images.githubusercontent.com/26613280/213881341-afc53897-251b-4d3e-8fbf-79928aa8a092.png)

@junah201 여기에 (마치 벨로그에 원래 있던 기능처럼?) 추가되면 좋을 것 같다는 생각을 남겨봅니다

**Comment by junah201** [comment]
#51
