### ISSUE TITLE
[Feature Suggestion] 자신의 블로그가 몇명에 의해 구독되고 있는지 알려주기

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#45]
### Idea

- A 가 B 의 블로그를 구독하고
- B 는 자신이 "1명이 당신을 구독중입니다"라는 것을 알 수 있을 때

→ B 가 글 작성에 더 힘이 나지 않을까 싶었습니다.

물론 B 도 이 플러그인을 쓸 때 알려줄 수 있을 것 같긴 합니다..

### Caveats

그런 정보를 제공하는게, A의 프라이버시 침해 소지가 있을지는 잘 모르겠습니다.

또한 이 플러그인을 이용하는 유저가 많아지기 전까진 큰 체감이 어려울 것입니다.

### Notes

또 생각해보니, 제3자에게도 좋은 정보가 되지 않을까 싶습니다.

예를 들면 C가 B의 블로그 글을 읽는데 상단에 "이 블로그는 1명(=A)이 구독중입니다"를 나타내는 기호/숫자/문장 이 나타나는 식으로요.

**Comment by junah201** [comment]
@roeniss 
이 기능은 원래도 생각하고 있었던 기능이고 이번에 전체적으로 기능 추가하면서 같이 넣어볼께요!

**Comment by junah201** [comment]
팔로워 수 표시 기능을 추가한 v1.1.0을 스토어에 업로드하였고, 승인 대기 중입니다.
배포가 완료되면 이슈를 종료하도록 할게요 !

**Comment by junah201** [comment]
![image](https://user-images.githubusercontent.com/75025529/214511712-748198d6-2ee9-4a4c-9169-38a0398a7536.png)

위 이미지와 같이 배포 완료되었습니다 !
