### ISSUE TITLE
[feature proposal] 내가 팔로우하는 블로그 목록을 알고 싶어요

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#46]
그냥 제가 못찾는건가요,,? 어느어느 채널들을 보고 있는지 알 수가 없어요

**Comment by junah201** [comment]
![image](https://user-images.githubusercontent.com/75025529/216892633-2176bf89-6816-4526-9b86-35270954388a.png)

![image](https://user-images.githubusercontent.com/75025529/216892802-7fb6b745-a20e-46f2-adc4-bbb773b4a002.png)


@roeniss 
오른쪽 위 Velog Helper 아이콘을 누르면 나오는 팝업창에서 블로그 목록을 확인할 수 있습니다 !!

**Comment by roeniss** [comment]
@junah201 
![CleanShot 2023-02-06 at 14 44 43@2x](https://user-images.githubusercontent.com/26613280/216892989-2973b824-d8b9-419b-9cb3-94c220471de0.png)

아;; 감사합니다. 급한 건은 아니지만, 버튼임을 나타낼 수 있는 border css 같은게 있으면 좋을 것 같습니다
