### ISSUE TITLE
스크롤바 UI 개선 건의드립니다 :)

### ISSUE THREAD

**Issue by joseph-106** [junah201/velog-helper#47]
![스크롤1](https://user-images.githubusercontent.com/61545957/217715307-8637ed61-eecb-455e-b98b-e4c8db8e102c.gif)
Before

![스크롤2](https://user-images.githubusercontent.com/61545957/217714912-f36202af-06f0-47a9-9da2-dd4835fa843d.gif)
After

[frontend/src/scroll.css]
```
::-webkit-scrollbar { width: 9px; height: 9px; }
::-webkit-scrollbar-button { display: none; }
::-webkit-scrollbar-track-piece { background-color: white; } 
::-webkit-scrollbar-thumb { border-radius: 9px; background-color: #c7c7c7; }
::-webkit-scrollbar-thumb:hover { background: #ababab; }
::-webkit-scrollbar-thumb:active { background: #808080; }
```

**Comment by junah201** [comment]
@joseph-106 
스크롤 바를 직접 마우스로 옮기는 일이 별로 없어서 너무 작아서 생기는 불편함에 대해서 잘 몰랐네요 ㅠ
PR 주시면 바로 적용하겠습니다 !!

**Comment by joseph-106** [comment]
PR 드렸습니다 ! 좋은 기능 만들어주셔서 감사합니다 ☺️

**Comment by junah201** [comment]
크롬 웹 스토어에 배포 후 적용 완료되었습니다.
기다리면 자동 업데이트가 되나, 아직 업데이트가 안되었다면 지웠다 설치해주시면 업데이트가 적용되어 있습니다.
감사합니다 !!

**Comment by joseph-106** [comment]
![image](https://user-images.githubusercontent.com/61545957/218060314-56a44b79-989d-4fce-a7d9-805c78750838.png)

적용이 넘나리 잘 되었네요 ~ 제가 더 감사합니다 ㅎㅎㅎ
