### ISSUE TITLE
[Bug] 크롬 업데이트 할 때 마다 안내 탭 등장

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#49]
https://3bxsddbb222i3zghh77frbcyoa0pbwan.lambda-url.ap-northeast-2.on.aws/guide

위 링크가 "Chrome update" 할 때마다 새 탭으로 등장합니다.

**Comment by junah201** [comment]
@roeniss 
`chrome.runtime.onInstalled` 함수가 단순히 맨처음 확장프로그램을 깔았을 때만 작동되는 줄 알았는데

> "install"
> "update"
> "chrome_update"
> "shared_module_update"

위 4가지 상황에서 작동해서, "install"에서만 작동되도록 수정해놓았습니다.
감사합니다 !!

**Comment by roeniss** [comment]
@junah201 감사합니다~ 배포될때 이슈 닫아주세요~~ (커밋 메시지에 #49 라고 쓰면 자동으로 레퍼런스 걸리고 클로즈된대요)
