### ISSUE TITLE
[건의] 메인화면에서 특정 유저의 게시물 안보이게 처리

### ISSUE THREAD

**Issue by roeniss** [junah201/velog-helper#50]
https://velog.io/ 의 화면에서 특정 유저의 게시물은 목록에서 지워버리는 기능을 건의합니다. 

(메일로 알람을 받으면서) 더 보고 싶은 분이 있는가하면, 별로 관심있는 주제가 아니라서 보고싶지 않은데 자꾸 메인 화면을 차지하는 글들도 있는 것 같습니다. 

velog-helper 라는 익스텐션 이름에 크게 엇나가지 않는 기능인 것 같아서 제안하게 되었어요.

단순히 블러 처리보다는 해당 게시물이 없는 것처럼 div 를 날려버리는 방법이면 좋겠습니다. 다행히 flex css 를 쓰기 때문에 줄은 알아서 맞춰질 거라 예상합니다.

**Comment by junah201** [comment]
#51
