### ISSUE TITLE
현재 즐겨찾기중인 유저 보여주기

### ISSUE THREAD

**Issue by myoun** [junah201/velog-helper#7]
현재 내가 누구를 즐겨찾기중인지 확인할 수 있으면 좋을 것 같습니다.

**Comment by junah201** [comment]
안녕하세요. @myoun 님.
저도 즐겨찾기 목록은 초기 구상부터 개발하려고 생각했던 기능이고 실제로 개발 중인 기능이에요.
![image](https://user-images.githubusercontent.com/75025529/185146432-c8679ff5-3cf4-4d5a-9118-7eb9b2790e43.png)
오른쪽 상단 즐겨찾기가 있는 탭에서 클릭시 나오는 창이 아직은 `Velog Helper`라고만 적힌 창만 나오지만
이 창에서 즐겨찾기 목록, 새 글 목록, 설정 등을 확인하고 관리할 수 있도록 개발하고 있어요.
혹시 더 좋은 아이디어 있으시면 반영하도록 하겠습니다 !!
이슈 감사합니다 👍👍👍

**Comment by junah201** [comment]
개발 완료 하였고, 크롬에 배포해놓았습니다. 한 3일 이내로 적용될꺼에요.

![image](https://user-images.githubusercontent.com/75025529/187683415-0a153130-8900-4adc-9851-2f31e5472c6a.png)

적용후에는 팝업창에서 확인할 수 있습니다.
